version: "3"

services:
  simple-server:
    image: simple/server
    ports:
      - 8081:8080
  web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./dist/schulung:/usr/share/nginx/html
